const User=require('../models/userModel')
const factory=require('./handlerFactory')
exports.getUser= factory.getOne(User)
exports.getUsers= factory.getAll(User)
exports.createUser= factory.createOne(User)
exports.updateUser= factory.updateOne(User)
exports.deleteUser= factory.deleteOne(User)